### ISSUE TITLE
Facebook content

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#11]
We need to get serious about sharing good content as well as our awesome work (and equally awesome photos). We have the start of a [Twitter presence](twitter.com/dwylhq) but not really one on Facebook.

**Comment by nelsonic** [comment]
@iteles you have the most experience with Fb Pages/Content. 
Obvs it would be better if we could get someone *passionate about* ***communications & community*** to do this work ... but until then...

**Comment by iteles** [comment]
Agreed!

**Comment by markwilliamfirth** [comment]
Will be reviewed as part of social media plan #244

**Comment by nelsonic** [comment]
"Social Media Plan" is 3 bullet points. 
![image](https://cloud.githubusercontent.com/assets/194400/26148146/9eb86a46-3aed-11e7-96ae-5fbb9efbc3c9.png)
no checklist, metrics, time estimate or any measure of progress.
I'm not _suggesting_ that Facebook content is a "_priority_", but our objective is to _capture_ the work in as _much_ detail as possible so that someone `else` can _easily_ pick it up.

**Comment by markwilliamfirth** [comment]
@nelsonic I'm aware and in agreement - it's because our social media plan is not a priority currently so the plan and therefore associated tasks have not been captured yet
