### ISSUE TITLE
Collaboration with HL

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#128]
**Involved in the conversations so far:** @iteles, @nelsonic @tonydaly 

+ [x] Initial phone call (@iteles)
+ [x] Initial meeting 
+ [x] Can build on the existing (not tested, not documented) code
+ [x] Can we build their list of features on time
  + Intended first 'release': 27th January
  + MVP: 7th April
+ [x] Budget (@iteles)
+ [x] Determining dwyl team
+ [x] Availability of our team 
  + Currently looks like we could start 12th - 14th December at the earliest (or January depending on project team)
+ [x] Send email containing all our thoughts and proposed budget.
+ [x] Follow-up telephone conversation.
+ [x] Initial workshop
+ [x] Schedule new year follow up workshop
+ [x] New Year workshop with @katbow

**Comment by nelsonic** [comment]
My contribution to the email sent to HL was/is:

Specific areas which are not currently being focussed on by the developers who are working on the HL app (where DWYL will show immediate and material added value):

Lean Methodology (Continuous Delivery & User-testing) - Users can easily get frustrated/dispirited when their needs are not met. We deliver value (small batches of features/improvements) to stakeholders on a continual basis. This process promotes a tighter feedback loop (validated learning) and leads to substantially less wasted effort. 
Transparency & Open Source - Developing technology in the open is considerably more difficult than “closed”; no corners can be cut on Documentation, Testing or Code Quality when the project will be visible to all. Documentation-Driven and Test-Driven Development has to be baked into the culture of the team/organisation otherwise it will always be an “afterthought” which leads to “bit rot”. Thankfully DWYL has focussed on writing Open Source code from the start so everyone on our team already has the mindset required to deliver great work and ensure other people in the wider community feel welcome to contribute!
Privacy & Security - Carefully considering the types of data used in/by the app and how to minimise the amount of Personally Identifiable information (PII) kept within HL’s domain is essential for the credibility of the app. We will encrypt all PII at rest and in transit using the highest level of the Advanced Encryption Standard (AES) and never store any PII on the client device to avoid embarrassment if a devices is lost/stolen/compromised. We firmly believe in our fiduciary duty to systematically address security questions in a human-friendly language to ensure all stakeholders (patient's, NHS Trust and any 3rd party developers/auditors) will have confidence in the app. Only by taking the “paranoid” approach to security we will have the solid foundation required to gain the adoption and subsequent critical mass required for “success”; few developers have this core belief.
Architecting for Maintainability, Scalability and Fault Tolerance - although the Spring framework is a good choice for most “Enterprise” Web Applications, some of the best-practices are not being followed in the code shared with us for our initial review (mhl.zip). While we are acutely aware of the dangers of “solving imaginary scaling issues” we feel that the micro-services approach (where small self-contained components of an app can be independently monitored and dynamically/horizontally scaled) will have several long-term benefits and be perceived by industry observers/experts as the “appropriate” choice.

**Comment by markwilliamfirth** [comment]
@iteles ok to close?
