### ISSUE TITLE
Company Legal Structure/Entity

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#142]
The DWYL legal entity is _currently_ a Private Limited Company (_limited by shares_).
We set it up that way simply to "_get it done quickly_" while still maintaining _complete_ flexibility to _change_ at a later data if required.

We have worked in:
+ **Registered Charities** (_lots of regulation but clear tax advantages_)
+ **Limited Liability Partnerships** (LLP) (_partners model but w/ limited liability. have cake & eat it!_)
+ **Cooperative Organisations** (_we bank with the Coop and prefer shopping at the Coop despite higher prices for no obvious benefit beyond warm-and-fuzzy-feeling_)
+ **Community Interest Company** (_we've helped setup two of these DTMO and F&C_) has clear benefits in terms of the _message_ it sends to stakeholders/members and good if you want to lock-in funds to a specific mission, but limited actual _benefit_ from a legal/taxation perspective.
+ Boring old (private/public) **Limited companies** of various sizes ... since I was a kid, I've always _liked_ the idea of floating "my" company on an _alternative_ marked/exchange without using an investment banker to pitch the prospectus i.e. DYI the IPO while we're still small so we can send actual trade-able shares to all stakeholders ... obvs we would only "offer" 25% of the stock so no "Private Equity" or "Activist Investor" would try and take over/hijack our mission by buying up a majority stake! but I still _like_ the idea ... and given that we're going for [Hyper Transparency](https://github.com/dwyl/hq/issues/140) in _any_ case the regulatory/reporting requirements of a PLC will be quite easy to meet. http://www.londonstockexchange.com/companies-and-advisors/main-market/rules/regulations.htm

> Are there any _other_ company legal structures we should consider in our discussion...?

## _Considerations_:

+ Perception of both "internal" and "_external_" stakeholders - what message does COOP/CIC/LLP/PLC send to each constituent of our community? are there people who will _only_ work with us if we're a COOP? Do we want to be part of the "_Digital Coop Movement_" (_which we are huge fans of BTW!_) ? or do we want to "_prove to the world that a PLC can be run for People & Planet before Profits, but still have a sustainable income for all members!_ ...?
+ Co-founder & team member remuneration (_are there any restrictions imposed by any of the 
+ Taxation (_what taxes are we liable for? could we pay no tax if we were a registered charity?_)

Another _related_ question but not the _focus_ of this discussion is _where_ should we be based?
(_given that "Brexit" will be a thing ... should we be based in London...?_) see: https://github.com/dwyl/hq/issues/141

## Pros of Staying Private

+ We can **focus** on our ***mission*** without having to "_answer_" any questions about why we are consistently investing for the long-term instead of maximising short-term gains.
+ Distracting reporting/regulatory requirements. (_how much of this can be automated_...?)

## Pros of a PLC

+ _Ironically_ if we _focus_ our IPO prospectus to _emphasise_ [***long-term-thinking***](http://www.asianbc.dk/Findings/Rapid-reactions/Very-longterm-strategies.aspx) the way many Japanese/Chinese/Korean companies have done we can set out our vision and get _many_ more people interested than if we remain closed/insular...
+ Financial Leverage to tackle bigger projects... https://github.com/dwyl/phase-two

**Comment by iteles** [comment]
In particular, I would like to investigate becoming a [B Corp](https://www.bcorporation.net/) and what it means/entails under the hood.

**Comment by nelsonic** [comment]
@iteles _fairly_ certain B Corp is only available for US-based Companies... 🤔 
but no reason we can't investigate `if` we can run a US entity... 👍

**Comment by markwilliamfirth** [comment]
Is this still something we're considering changing?

**Comment by iteles** [comment]
Yes. Bumping down the priority until I have communicated the plan for 2017 more clearly and then we can pick this up again in light of that.

**Comment by markwilliamfirth** [comment]
I don't think this is a low priority considering it is integral to the organisation and vision

Are we not planning to transition asap? Before the Future of dwyl event?

**Comment by iteles** [comment]
@markwilliamfirth I disagree. What matters is how we conduct ourselves as an organisation according to our values and making our model sustainable. So far we haven't been limited by our legal status. I think a legal structure is a distraction at this stage and our focus should be on our 2017 plans.

Once this becomes an impediment, it will become a higher priority.

**Comment by markwilliamfirth** [comment]
As I understand it the plans outline that it is people first, not profit first, which suggests to me that we're currently operating under the wrong company structure.

**Comment by iteles** [comment]
It's a technicality at this stage. We shouldn't be wasting time on this.

**Comment by markwilliamfirth** [comment]
For me it communicates a confusing message when our company structure doesn't reflect the values we preach. I wouldn't say it was a waste of time - it's definitely a concern for me. I would argue that we should agree whether we are operating under the wrong structure and which structure we should be operating under as a priority - it says a lot about our organisation. This, after all, is the reason we use to cooperative bank when dealing with clients and we offer special discounts to organisations with charitable status. It's something that we value so it seems silly that we wouldn't look at ourselves in regard to the same issue.

**Comment by markwilliamfirth** [comment]
b-corp assessment requires mission statement
https://github.com/dwyl/start-here/issues/116

**Comment by iteles** [comment]
As discussed on Friday, let's put **1 hour** into investing B-Corps, time and costs involved in setup and maintenance and then take it from there.

**Comment by iteles** [comment]
Seems like finding one hour proved difficult between March and November.

@rub1e Could you please find an hour or two (as needed) to do the research on this this week?

+ [ ] Brief description of B-Corps
+ [ ] Requirements that need to be met to become one (could be a link to an existing list)
+ [ ] Time & costs involved in setup
+ [ ] Time & costs involved in maintenance

**Comment by rub1e** [comment]
## What is a B Corp?

> B Corps are to business as FairTrade is to coffee

B Corp status is a **private certification given to for-profit companies** which score well on a *social impact assessment*. 

This involves demonstrating **positive social and environmental impact, having good accounting standards, and being transparent to the public**. 

Put another way, you could say it's a rejection of Milton Friedman's famous quote: "There is one and only one social responsibility of business - to increase its profits."

This is because *the Friedman view means your shareholders are your stakeholders*; whereas **a B Corp would consider the following as stakeholders**: *your employees, your suppliers, the environment, the local community*, and so on.

## How to become a B Corp

* Complete the [online self-assessment](http://bimpactassessment.net/)
* Follow [these steps](http://www.bcorporation.net/sites/default/files/documents/uk/UK_Guide_to_the_Legal_Test_for_Prospective_B_Corps_in_the_UK_21May15.pdf) and amend Company Articles / Constitution as needed
* Pay for the official certification (c. £1,000 every two years)
* Sign a Declaration of Interdependence (below)

![Declaration](https://www.bcorporation.net/sites/default/files/2015-B-Corp_Declaration-2015-top.png)

## Setup

*dwyl would almost certainly past the assessment test as-is*, so the main task would be to change some of *the language in the Articles of Association*. 

Estimate for a company of dwyl's size - **10 hours max** (includes taking the assessment, amending the Articles, checking the Articles, filing with Companies House, paying for the certification). Plus **fee of £1,000**.

(That said, there is a 10% chance of being randomly selected for an on-site review.)

## Maintenance

Recertification happens every two years so *very little maintenance required*. 

It might be an idea to appoint someone whose job it is to ensure dwyl is reaping the rewards of the B Corp badge and getting the most out of it, being part of the community etc.

**Comment by rub1e** [comment]
My *personal* view is that it would be lovely if more companies adopted the [triple bottom line](https://en.wikipedia.org/wiki/Triple_bottom_line) view of business **(People, Planet, Profit)**

But dwyl is *already* a Purposeful company with strong socially responsible values - *I don't see this changing the way dwyl thinks or behaves as a company*.

So the question is really **"Is there any benefit to paying for the B Corp Badge?"**

My instinct is to be suspicious of certifying bodies like Fair Trade, which always seem to benefit the certifying body more than the farmers they're supposed to be championing.

But if paying £1000 for the Badge makes people notice dwyl, or gets people to write about us etc. then it's a steal at twice the price! (And unfortunately there's not really enough evidence out there on the impact the badge has on revenue...)

**Discuss...**

**Comment by iteles** [comment]
Right now, given the size of our company, there is no particular benefit to be derived from becoming a B Corp specifically. Given that this is the only other legal structure we would consider, I am closing this issue and it can be re-opened if it becomes relevant again.
