### ISSUE TITLE
What is our One Metric that Matters ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#149]
What is our "***One Metric that Matters***" http://leananalyticsbook.com/one-metric-that-matters/ ?
What is the one thing we want to _measure_ @dwyl in order to do _more_ of _that_ thing...?

I _really_ like the fact that GitHub let's you _filter_ based on the "reactions" on an issue now:
![github-filter-on-most-reactions](https://cloud.githubusercontent.com/assets/194400/21422257/ca5b48b2-c82e-11e6-9334-abeb3081cb68.png)
See: https://github.com/dwyl/hq/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-heart-desc

**Comment by Jbarget** [comment]
I dont have the answer to the question but I find this such an interesting discussion after being introduced to it by [Tristan Harris](https://twitter.com/tristanharris?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor) at web summit. 

Same talk here - https://www.youtube.com/watch?v=3OhMJh8IKbE

He has set up an initiative called [Time Well Spent](http://www.timewellspent.io/) to combat the current trend in "successful" companies's focus being on the amount of Time Spent on their products by users. Makes so much sense.

**Comment by nelsonic** [comment]
@Jbarget so _stoked_ you got a chance to listen to Tristan @ WebSummit! 🎉 
just that _alone_ was worth your trip to Lisbon! ✈️ 
We were discussing this the other day and concluded we need to have the "Time Well Spent" design  philosophy at the _heart_ of what we are building see: https://github.com/dwyl/time/issues/187 ❤️  ✅ 

Meanwhile the 🔍  for an OMTM for DWYL _continues_ ... 
**Question**: how can we _formulate_ a **Metric** (_something measurable_) out of the "Time Well Spent" philosophy? 🤔

**Comment by markwilliamfirth** [comment]
I think one metric that might be interesting and/or useful would be **Product Metabolism**. Still looking into it and will update more later, but leaving this here in case anyone has any thoughts on it or other metrics.

**Comment by markwilliamfirth** [comment]
Is there a way to track productivity as a metric? Maybe reflect on our productivity everyday and assign a quantitive amount to it as well as quantitative comments reflecting on the day?

**Comment by nelsonic** [comment]
I'd rather track happiness than productivity. but both are equally "_subjective_" ...
@iteles your thoughts on this would be welcome. 👍

**Comment by markwilliamfirth** [comment]
We can set up NPS scoring quite easily

**Comment by markwilliamfirth** [comment]
@iteles your thoughts?

**Comment by nelsonic** [comment]
HI @markwilliamfirth, I think we like the _idea_ of the NPS ... 
we just don't like the way most companies _implement_ it ...
We don't want to make tracking happiness or "satisfaction" a "_formal_" thing people do because they _have_ to ... it's like telling people to Tweet. if they don't _want_ to do it then it will _always_ feel like a "_chore_".

**Comment by markwilliamfirth** [comment]
@nelsonic how would you like to track it?

**Comment by markwilliamfirth** [comment]
NPS tool I mentioned -> https://promoter.io

**Comment by markwilliamfirth** [comment]
@nelsonic see comment: https://github.com/dwyl/hq/issues/149#issuecomment-282709732

did you have further thoughts about how you wanted to implement NPS?

**Comment by mantagen** [comment]
@Jbarget @nelsonic 
I recommend this podcast https://www.youtube.com/watch?v=jlPF9_1VIso

**Comment by mantagen** [comment]
That's what 1.5 speed is there for! :)

**Comment by iteles** [comment]
I've been going through this and discussing it with various people over the last few months, but this definitely needs to be codified.

The **most important** thing for people to _realise_ is that 'One Metric that Matters' doesn't tie you into that metric forever more. As dwyl and our shared objectives evolve, **we _encourage_ a periodic review of these**.

There are (and should be) OMTMs for each branch of the organisation and for individuals as well. There will be more detailed objectives, but it's _crucial_ to have an OMTM so that there is a **clear focus and expectation**.

## _Individual_ Team Members

#### OMTM: Frequency and quantity of _Shared_ learning.

Learning how to do something _just_ so you can solve a particular problem on a project is _fine_, but if the knowledge goes no further than an individual, how useful is it and how quickly will you forget it?

> We work together. We build each other up.

The people who _share_ what they know (_i.e. write/contribute to docs, blog posts, records screen casts and write books_) are the ones who _vastly_ exceed their peers. Sharing _immediately_ demonstrates to your peers (_and both current & future employers/team mates_) that you are a "Lead Developer". 

Remember that:
+ There's a _high_ degree of certainty you will forget the details of how you "_solved_" something
between _writing_ the code and returning to it weeks later. Working your way through your code will waste your _own_ time re-grokking it
+ 'Others' is not just people within your physical reach. We aim to be a remote-first organisation (meaning you can work from _anywhere_) and we already have a remote community of over 350+ people _actively contributing_ to your knowledge
+ Your own learning is **solidified** by teaching
+ When someone takes an hour of their time to write up something that took them a day or a _week_ to figure out and learn, you can now learn it in 30 minutes. Think about _how much time you have saved_! Pay it forward.


### Shared Learning - How?
Contribute in the form of `dwyl/learn-...` enhancements and implementations of these learnings on dwyl modules/products.

Don't take our word for it, here's **Mattias Petter Johansson** from Spotify:

[![image](https://cloud.githubusercontent.com/assets/194400/26407306/a78b5174-4092-11e7-85de-d934ede8257a.png)](https://youtu.be/RleN-6uMF04)
https://youtu.be/RleN-6uMF04

## _All_ Projects & Product

#### OMTM: Number of _Re-useable_ Components created (or used) in the project

If we are not writing _re-useable_ code we are building everything "_from scratch_" each time. 

This is worse for the client/customer/user because it takes longer to build (and is therefore more expensive) and longer to start getting actionable feedback from user testing.
It's worse for all _future_ projects and team mates because it **wastes** _future_ time of people and projects who have to constantly rewrite similar things.    
It damages our chances of working with clients who are doing _awesome_ things that have a _real_ social impact because these are also often the clients with the least budget.

### Number of re-useable components - How?
Track this and document at the end of each project.

## Services Projects

#### OMTM: _User Satisfaction_ with the end-result.
or, if we can't get access to this data:
#### Proxy OMTM: _Product Owner Satisfaction_ in the form of a quote and rating

Both of these metrics will feed into the relevant  [**case study**](https://github.com/dwyl/hq/issues/274) for the project/client.

We then also want to integrate that feedback into our processes to make what we do better both for _current_ and _future_ clients.

### User satisfaction/PO satisfaction - How?
In the short term, through surveys that are sent to POs at the end of a project.   
We need to work with our clients to develop a way to help them measure end user satisfaction.



##  dwyl Products

#### OMTM: Number of people who have _used_ the products to **save time** in their lives and feel more _fulfilled_.

Our goal as an organisation is to "[Empower people to sustainably unlock their potential and pursue their passion.](https://github.com/dwyl/phase-two#our-goalmission)"

Our products will be a conduit for this goal so we want to ensure they are making strides towards it.


## Operations

#### OMTM: Ensuring all operating (financial and human) information is available in near realtime through automatisation of systems.

I see the key task towards this as _automating_ as many systems as possible so the data flows and ***minimises repetitive manual input*** wherever _possible_. HOWEVER, we also need to do this in such a way that ***minimises tooling*** and keeps to our 'single source of truth' principle to ensure **frictionless updating**.

"Operations" is not _directly_ responsible for bringing in revenue or _creating_ the product, but is **critical** to _saving everyone time_ and ensuring that **all** of the necessary information is _readily_ available so that **informed/good decisions can be made** e.g. #321.


@markwilliamfirth @nelsonic NPS is a good metric we _should_ track in the _near_ future, 
but in the _short_ term, we have a simple way we can collect feedback _today_: https://github.com/dwyl/feedback ❤️

**Comment by nelsonic** [comment]
@iteles I saw you _start_ to transfer these OMTMs to a markdown file ... but guessing you got lured away to a more urgent task. please assign PR when ready. thanks! 👍
