### ISSUE TITLE
Environment No. 16

### ISSUE THREAD

**Issue by Jbarget** [dwyl/hq#160]
An issue dedicated to making number 16 a clean, organised environment to work:

- [ ] Coat hooks 
- [ ] Dish rack - measurements needed!
- [x] Towel bin (for dirty towels to be washed)
- [ ] Shelves for kitchen area
- [x] Dish sponges
- [x] Sponge cloths
- [ ] Remove broken fridge
- [ ] Lighting https://github.com/dwyl/hq/issues/156

**Comment by Jbarget** [comment]
@iteles options for coat hooks

cheapest: https://www.amazon.co.uk/OGORI-Hooks-Stainless-Clothes-Hanger/dp/B01DBI22VC/ref=sr_1_3?ie=UTF8&qid=1484586317&sr=8-3&keywords=coat+hooks

alternative: https://www.amazon.co.uk/Headbourne-Azhr0644-6-Heavy-Chrome-Wooden/dp/B00BWS3ZEC/ref=sr_1_50?ie=UTF8&qid=1484586360&sr=8-50&keywords=coat+hooks

**Comment by Jbarget** [comment]
I think we can arrange for tower hamlets to pick up the broken fridge (might be for residential only):

http://www.towerhamlets.gov.uk/lgnl/environment_and_planning/recycling_and_waste/recycling_and_waste_at_home/large_items.aspx

**Comment by iteles** [comment]
@Jbarget We *are* residential at hq ;)

On the coat hooks, is anyone going to Ikea soon? I'm quite partial to these because they actually have the *space* to hang winter coats without everything falling off the hooks every time someone adds a new one (also, a little more breathing room in case it's been raining)...
http://www.ikea.com/gb/en/products/small-storage-organisers/hooks-hangers/blecka-hook-stainless-steel-art-30152676/

**Comment by Jbarget** [comment]
sounds good but im not heading to ikea any time soon. Would you go to Ikea for these?

**Comment by iteles** [comment]
Moved to https://github.com/dwyl/quietspace/issues/2
