### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by anweshknayak** [dwyl/hq#165]
Who all are developing ? can I help ?
Tech Stack ?

**Comment by nelsonic** [comment]
@anweshknayak thanks for opening an issue to ask a question & welcome to DWYL! 
(_if you don't mind us asking: how did you find us_?)

Our _current_ tech stack is: https://github.com/dwyl/technology-stack
But we are in the _process_ of moving to `elm-lang` for the front-end: https://github.com/dwyl/learn-elm

You can _certainly_ help! 
Question is: what do you _want_ to help with?

**Comment by anweshknayak** [comment]
Found somewhere in reddit.com. I am familiar with JS/Python. Can try my hands on anything related to web-development side.

**Comment by nelsonic** [comment]
@anweshknayak _sweet_. 🍭 
Redit. wow. I'd _love_ to read the post where dwyl was mentioned. (_please share if you remember it_)

Ok, if you feel confident with JS Promises knowledge you could take a look at this PR: https://github.com/dwyl/aws-sdk-mock/pull/63 
Essentially we need to _confirm_ that it conforms to Promises spec: https://promisesaplus.com
so that we can merge the PR.

***or*** if you have an appetite for learning about the AWS Lambda "Serverless" Architecture, you could take a look at: https://github.com/dwyl/learn-aws-lambda
we were thinking of migrating it to use "GitBook" so that people could read it online as a book with chapters: https://github.com/dwyl/learn-aws-lambda/issues/57

**Comment by markwilliamfirth** [comment]
@nelsonic I thought you said Reddit didn't matter? #248  ;)

**Comment by nelsonic** [comment]
@markwilliamfirth Redit has it's purpose ... I've not used it since it was sold (_out_).
@anweshknayak can this be closed?
