### ISSUE TITLE
Second Garage?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#21]
Given how *cheap* the space is, we should attempt to get a *second* garage on the estate.
Can you please contact the council about this?
There are quite a few that are empty on the estate ... It needs to come from you as I'm already in their database.
relates to: #20 (*screen printer* ...)

**Comment by iteles** [comment]
I called today but didn't get through. Making this happen tomorrow without fail.

**Comment by iteles** [comment]
Officially on the waiting list :+1: 

<img width="970" alt="mdc-second-garage-application" src="https://cloud.githubusercontent.com/assets/4185328/10243386/2c0fb092-68f0-11e5-8ef2-2f37dda137b3.png">

**Comment by nelsonic** [comment]
Follow up call to check waiting time?

**Comment by iteles** [comment]
I did that already this morning. 

![computer-says-no](http://i2.wp.com/www.whaleoil.co.nz/wp-content/uploads/2015/09/computer-says-no.jpg?zoom=2&fit=500%2C331)

**Comment by nelsonic** [comment]
Right, I got the same at the time. but we need to have a morning task to call them like every day. or if you have the patience cycle out there one day its not too much of detour on the way to FAC ...

**Comment by iteles** [comment]
Right, but the waiting time is "there are no garages and the waiting lists are long. I can't tell you how long it will take because people can stay in garages for 5 or 10 years if they want so I don't know when one will become available".

I can call every day to find out if we've moved up in the list if you like. I'll try it for a week.

**Comment by nelsonic** [comment]
I think the *in-person* approach might be more effective ...

**Comment by iteles** [comment]
Tuesday or Wednesday morning cycle in then :+1:

**Comment by iteles** [comment]
Had a a lovely chat with the garages team earlier today.

Here's what we know:
+ We're 1106th on the list for garages in Camberwell (she led with this...)
+ We're 10th on the list for garages in D'Eynsford
+ There are works due to be completed by mid December that should create another 5 or so garages on the estate

**Comment by nelsonic** [comment]
Right. 
would have been worth doing this earlier... 
![captain-hindsight](https://cloud.githubusercontent.com/assets/194400/10278313/2551090c-6b54-11e5-8967-227a03aa7a90.jpg)

**Comment by iteles** [comment]
Just spoke to Leanne at the council and she said I will probably be able to get one sometime in March 2016 :+1:

**Comment by iteles** [comment]
Well that was quick. Going to see the possible new garage on Tuesday.
Didn't really want to be paying for one before xmas but...

**Comment by nelsonic** [comment]
Yeah, its lame to "waste" the money... :money_with_wings: 
but it will pay for its-self soon enough. :+1:

**Comment by nelsonic** [comment]
Closing this. Sad we didn't sit down and write out a goal/plan for why a second Garage would be _useful_ for our project ... but given that we _already have_ space that is not fully utilised, maybe we can focus on that instead.
