### ISSUE TITLE
Business Health Insurance

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#215]
[These](https://www.securehealth.co.uk/) were the people that called us the other day

Do we want company health insurance? Later down the line maybe?

**Comment by nelsonic** [comment]
@markwilliamfirth this is _especially_ relevant for our remote people. or for people travelling.
let's keep this issue open and if anyone wants to comment or help investigate the options, they are welcome to do so. I would _remove_ the priority label and simply state that because we are _lucky_ enough to live in a country that has "free" healthcare that health insurance is not a high priority for us. but for anyone living in a country without "free" NHS they are welcome to investigate and inform us of the options. 👍

**Comment by markwilliamfirth** [comment]
Closed in favour of #256
