### ISSUE TITLE
Github May Terminate

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#216]
https://help.github.com/articles/github-terms-of-service-draft/#3-github-may-terminate

If Time and Tudo are being intimately linked with Github and all of our company information is on Github - is this a potential issue or highly unlikely to ever be a problem?

**Comment by nelsonic** [comment]
@markwilliamfirth we are _acutely_ aware of the "risk" of putting _all_ our info on GitHub.

> This question is addressed in: https://github.com/dwyl/github-reference/issues/15

Part of "Tudo" will be to _mirror_ all the data in GitHub in a Local Cache i.e. _continuous backup_.

So that if GitHub ever decided to "_terminate_" our service it would _very much_ be their loss as we would be able to continue working without them. 👍 

In fact, longer term we have the option of _hosting_ our own "GitLab" instance if we chose.
so we have a _reasonable_ amount of redundancy. ✅

**Comment by markwilliamfirth** [comment]
Seems like in the long term we should be aiming to create our own platform though?

**Comment by markwilliamfirth** [comment]
@nelsonic why was Github chosen? Is it a stopgap for a dwyl platform? Why was Github preferred over alternatives, such as Jira?

**Comment by nelsonic** [comment]
@markwilliamfirth good question.
find me a developer who _enjoys_ using Jira and I will switch to it. 😉 
![image](https://cloud.githubusercontent.com/assets/194400/23978985/b6cf6c90-09ee-11e7-8f9f-c18cbb2185a6.png)
![image](https://cloud.githubusercontent.com/assets/194400/23979006/d81eea1a-09ee-11e7-96a9-41e766da0e4b.png)

I did not create the "meme" the internet is _full_ of posts (_rants?_) about how bad Jira is...
ask @jackcarlisle or @jruts how they feel about it. 😆 
The number of clicks/steps required to update a "Ticket" in Jira is _always_ more than 3. 
@ TC creating a new ticket had 23 fields. no word of a lie. it was a dystopian joke designed to suck the life out of the most valuable people in the company (_developers_) just so that managers (_people who get paid to ask other others "is it done yet"_) could see a "burn down chart" of all the (_non user-focussed_) tasks ... 

We don't think GitHub is the "best" or even that it's "_better_" than GitLab (_for example_) 
but the decision was made because it's the technical team workflow adopted by _most_ of the industry. Most Open Source projects use GitHub for their code and issues, there's a critical mass that means if we want to get contributions from a world-wide community of people, we don't have to re-educate people to use a different system; every developer already knows how to use GitHub. ✅ 

For example: Most of the modules on NPM (Node.js) or Hex.pm (Elixir) are stored on GitHub.
So if we want to ask the developers of our tools a question (_and link it to the story we are working on for a given project/feature_) it's _much_ easier to do everything on GitHub.

We don't intend to move _off_ GitHub in the _near_ future. Everything we do on GitHub is Open Source so @dwyl does not pay a _penny_ for the service, so there's no "_downside_" to using it.

And once we have a way of aggregating, sorting and prioritising all our issues across all projects and client work https://github.com/dwyl/tudo we will have a _much_ more streamlined workflow. 👍 

Hope that answers your question. ❤️

**Comment by jruts** [comment]
@markwilliamfirth you do **not** want to use JIRA, trust me.

**Comment by sohilpandya** [comment]
![taken](https://answers.atlassian.com/download/attachments/43715414/53361318.jpg?version=1&modificationDate=1477560556238&api=v2)

**Comment by markwilliamfirth** [comment]
@nelsonic Would hosting our own GitLab instance mean that we maintained control of the service? (GitLab wouldn't be able to shut our service down? etc)

Is the main downside to GitLab what you mentioned above?
>[On GitHub] there's a critical mass that means if we want to get contributions from a world-wide community of people, we don't have to re-educate people to use a different system; every developer already knows how to use GitHub.

Or would the GitLab instance mirror GitHub and they would both run simultaneously?

**Comment by jruts** [comment]
@markwilliamfirth why would you host something yourself if you can use the cloud? A simple backup mechanism to make sure you do not lose any data when GitHub would shut down is more than enough.

Furthermore I do not think GitHub will just drop their services without any form of announcement or warning. 

So I would not worry too much. If GitHub gives you what you need or want then just stick with it and do you backups. Maintaining your own servers with git capabilities will take you a lot more effort to maintain.

**Comment by jackcarlisle** [comment]
@markwilliamfirth commenting on the above https://github.com/dwyl/hq/issues/216#issuecomment-286939544 

JIRA is **excruciating**. It's got far too much functionality and the dashboard is incredibly crowded. This is all coupled with the fact that it isn't really that intuitive to use 👎

**Comment by jackcarlisle** [comment]
![jira](https://s-media-cache-ak0.pinimg.com/originals/9b/fa/91/9bfa9157fce710951baba54ef0d89581.jpg)

### for @sohilpandya

**Comment by markwilliamfirth** [comment]
@jruts the reason I'm asking is because it's integral to the long-term business plan, so although highly unlikely to occur and somewhat solved by a backup, it's something that needs to be thought about when establishing the long-term vision. I have no idea how GitLab plays into this or why is was mentioned as an [option](https://github.com/dwyl/hq/issues/216#issuecomment-278226663) in the long-term - hence my question for further clarification above.

@jackcarlisle et al - yes I'm seeing a lot of dislike for Jira - thanks everyone for clarifying that it's not a great alternative. The reason I mentioned it was because I had been told by someone that it was an alternative platform for a single source of truth development management platform. Do not fear - we are not changing to Jira - just trying to understand the reasoning in choice of current tech tools 👍

**Comment by iteles** [comment]
I think this would be a good stop gap for the short-medium term as mentioned a few times above :blush: : https://github.com/dwyl/github-backup
 I believe @jbarget and @des-des are looking into this as part of https://github.com/dwyl/tudo/issues/146 🕺
