### ISSUE TITLE
Discussion Follow-up

### ISSUE THREAD

**Issue by jackcarlisle** [dwyl/hq#217]
@nelsonic @iteles  

Following on from our discussion earlier today, I've been thinking about what areas within DWYL I'd be most interested in pursuing in the coming weeks and months. These areas include (but are not limited to):

- Learning the *[New Stack](https://github.com/dwyl/technology-stack/issues/37)*
- Product Development
- Content creation

I would really value your opinion on where you feel I would have the greatest impact and what the best steps would be moving forward?

I'm also keen to learn more about full-time opportunities within the company.

Thanks!

**Comment by nelsonic** [comment]
@jackcarlisle I `promise` I'm not "_ignoring_" you on this ... 
My "_job_" is to deliver for our _current_ clients and to make sure we have a good technical direction for our products/services (_and to not fall behind on my own technical knowledge/skills!_)
We _absolutely_ need to look into offering people "_full time contracts_" and the _best_ people to speak to on this are Ines & Mark who are putting together the future/biz plans.
Once you are comfortable/confident with "New Stack" please post a comment here with an update!
We have quite a _few_ mini-projects in mind that we need to flesh out. 
Meanwhile if you're "_bored_" please feel free to improve the content in _any_ of the `learn-...` tutorials because we're going to need to get _many_ people up-to-speed with what we do and _how_ we work as a team. 👍 
Also, if you haven't read ["Sprint"](https://www.amazon.co.uk/Sprint-Solve-Problems-Test-Ideas/dp/0593076117) and ["Lean Analytics"](https://www.amazon.co.uk/Lean-Analytics-Better-Startup-OReilly/dp/1449335675) please add them to your list!

**Comment by jackcarlisle** [comment]
@nelsonic ok great, thank you! 

Will update you with the "New Stack" progress over the coming days and extend the `learn-` repos as and when I can.

Just ordered those two books as well so can't wait to get stuck into those. 

![screen shot 2017-02-10 at 10 21 46](https://cloud.githubusercontent.com/assets/12450298/22823304/ea6ffb2a-ef7a-11e6-9797-ffad6a9e7624.png)
