### ISSUE TITLE
Inês Bio

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#225]
Inês needs a standard bio for conferences, talks and events.

@iteles could you send me the snippets you mentioned so we can construct your bio?

**Comment by iteles** [comment]
Turns out this is all I could find and it's useless, we'll need to write something up!
It was used for a talk where I was discussing F&C rather than dwyl.

Ines is the co-founder of dwyl.io and the a director at Founders & Coders, the UK’s only free 16 week, in-person, full stack Javascript coding bootcamp. She also runs the London chapter of Ladies of Code and is a developer, whose favourite topics are accessibility, education and women in tech.

**Comment by markwilliamfirth** [comment]
[Drafting document](https://docs.google.com/document/d/1i5DCkcgf-cB3S8fluB2UXw4vmtdQCnpshhHileZePXQ/edit)

**Comment by markwilliamfirth** [comment]
@iteles if you had to describe your background before tech in a few lines how would you do so? Maybe Something about Accenture?

e.g.

>Prior to DWYL, Ines spent X years in digital consulting where she ____.

**Comment by markwilliamfirth** [comment]
[Done](https://docs.google.com/document/d/1i5DCkcgf-cB3S8fluB2UXw4vmtdQCnpshhHileZePXQ/edit). Closed for now until redraft necessary.
