### ISSUE TITLE
DWYL Demo Email Address?

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#233]
Can we create a `dwyl.io` email for client demo purposes?

I think this might be beneficial because it:
- Will look more professional to the client
- Maintain the privacy of employees and contractors whether that be the privacy of their personal email or their `dwyl.io` company email
- Prevent potential situations where an inbox needs to be shown in a demo and an inappropriate email appears in the inbox being shown

@iteles thoughts?

**Comment by iteles** [comment]
Each project has at least one test email account set up specifically for that project so that we can pass the ownership of this on to the client at the end of the project. 

It is recommended but not enforced that this email address is used for demos. 

Not entirely sure where it's best to document this, need to have a think!

**Comment by iteles** [comment]
@markwilliamfirth Forgot to reassign this to you! Can we close this?
