### ISSUE TITLE
Microsoft Office License

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#263]
Do we have an office license for Mac? If not, can we get one?

**Comment by nelsonic** [comment]
@markwilliamfirth we use Google Docs for all "Office-related" stuff. 
Are you attempting to edit a Proprietary Microsoft format for a specific doc?

**Comment by markwilliamfirth** [comment]
@nelsonic yes I want to make edits to an already existing word doc. Converting to google docs will disrupt the formatting

**Comment by iteles** [comment]
@markwilliamfirth Is this for a dwyl document or a document we are sharing with a client? 
If it's for something to be used as a dwyl document, it will need to be converted to Google Docs for ease, collaboration and accessibility.

For every contract/document/NDA/agreement over the course of the last year, we have used Google Docs. Changes in formatting so far have been minimal enough that they haven't made a difference when I say 'this is just the way we work' to our clients.

If you still think this is definitely required, then let's get it 👍

**Comment by markwilliamfirth** [comment]
@nelsonic has a USB for me with the programs on - can I come and collect it from you Nelson? :D

**Comment by nelsonic** [comment]
@markwilliamfirth yeah, @iteles has the USB which is a _bootable_ OS with all the software.
Running MacOS X off a USB "thumb drive" isn't ideal (_it's not exactly fast_)
So the next steps would be to:
+ try running off the USB until you get sick of how long it takes to load...
+ backup everything you already have on your MacBookPro onto the USB (_I can show you how if you need_)
+ Then "restore" your MacBookPro from the USB so that it "_wipes_" your hard drive and gives you a new OS with all the programs you want/need. 👍

**Comment by iteles** [comment]
I have no idea why this is a priority-1?

**Comment by nelsonic** [comment]
@iteles I think it was a blocker for getting some work done for @markwilliamfirth ... 😞 
@markwilliamfirth please confirm if you were able to Boot off the USB drive and use MS Office. ❓ 
We can re-configure your Mac to have all the apps by default if you have 1h of time this week... 👍 
Hopefully we can get this sorted. ✅
