### ISSUE TITLE
Contractor Information

### ISSUE THREAD

**Issue by ghost** [dwyl/hq#269]
Inês to send Mark:

- [ ] Start dates for all contractors (pre Mark joining)
- [ ] Contracts for all contractors (pre Mark joining)

**Comment by iteles** [comment]
@markwilliamfirth Yeouch, this one definitely got lost.

All previous contracts should be in the google drive from early this year but I will double check.

In order to gauge priority (there are 26 priority 1 issues assigned to me and 38 priority 2) could you please clarify/record what this historical information will be useful for?

I have to do some digging for #112 so can do at least a portion of this simultaneously.

**Comment by markwilliamfirth** [comment]
@iteles this issue isn't high priority, it's for our records

from what I can see you have 15 p1s and 28 p2s (https://github.com/issues?utf8=%E2%9C%93&q=assignee%3Aiteles+is%3Aopen+label%3Apriority-1+-label%3Adependency+user%3Adwyl)

**Comment by iteles** [comment]
@markwilliamfirth Within the dwyl repos, that's correct. Those are not the only repos where tasks are assigned to me.
Thanks for clarifying.

**Comment by markwilliamfirth** [comment]
@iteles I can't seem to see those repos - are they private repos? The only other p1 I can see is cul-2016 quiz issue 553

**Comment by iteles** [comment]
There's a lot of noise in this issue. Closing.
