### ISSUE TITLE
Meetings

### ISSUE THREAD

**Issue by ghost** [dwyl/hq#297]
It was decided last week that due to the organisation's value of hyper-transparency we need to record discussions and outcomes of Director meetings on GitHub for everyone to be involved. Given this is a requirement it makes more sense for 'meetings' to be conducted online where discussion is recorded.

Until recently we've been following a Monday & Friday meeting model, which was introduced in February by Mark, but this process results in shortened minutes that don't allow others to have the full picture and goes against our hyper-transparency value.

We need to agree and decide on a new process to conduct meetings that is both efficient and hyper-transparent. If everything is on GitHub and continuously discussed with a priority then maybe meetings aren't a requirement anymore?

If this is the case we need a new system to agree and discuss weekly priorities - building on conversations with @iteles last week I would suggest @iteles @nelsonic and @markwilliamfirth assign all of their GitHub tasks a priority and add them to weekly sprints. Priorities can then be discussed on GitHub.

@iteles @nelsonic what thoughts do you have on the above?

**Comment by iteles** [comment]
@markwilliamfirth This is a GREAT idea 💡 :tada:
Our Friday meetings with the 3 of us discussing company priorities and our week's retrospective should absolutely follow this. Let's do it from this week 👍 

Our Monday meetings are 1-on-1 sessions and I feel they are much more meant for personal feedback and priority setting. I think this requires an _equal_ level of transparency in terms of having an agenda consisting of issues, updating them throughout the meeting and spending the last 7 minutes of the meeting should be spent making sure all actions and updates are on Github.
_However_, given that there is a personal feedback portion to this meeting, we need to know how best to deal with it as I don't think that leaving that until the end is fruitful (better in context) and I'm not sure we're quite ready for feedback on individuals to be as transparent as we are as a company! 

@nelsonic What are your insights here?

**Comment by markwilliamfirth** [comment]
@nelsonic what are your thoughts on this? In-person meetings / vs github meetings

**Comment by markwilliamfirth** [comment]
I have created a new company priorities project here https://github.com/orgs/dwyl/projects/6

Here we can continuously review and track company priorities, each priority should be recorded as an `epic`, epics link to issues (tasks)

**Comment by iteles** [comment]
I have re-read the above based on a mini-conversation we had yesterday and I think I go the wrong end of the stick :/

You were suggesting that we have discussions on github in lieu of meetings and I _thought_ you were suggesting that we _record_ our meetings (screencasting as we do with standups for example) and then add our conclusions as actions to github.

I personally _don't_ think we should have 'github meetings', i.e. only discuss things on github instead of the 3 of us meeting on a Friday because:
+ The team of directors needs to operate as a _unit_, build camraderie and rapport to ensure we are all pulling in the same direction and are agreed on the direction of the company - this is much harder to do if we only ever speak through text on github and we need to take the road of less friction for the good of the organisation (hangouts and in-person meetings)
  + The weekly retrospectives here are interesting and useful for this purpose - we should add a question though: 'Which one thing have you done this week that will help dwyl progress towards it's goals?'
+ We sometimes have 20 minute discussions on a topic - doing that in github is not productive, can never be followed and has a _huge_ tendency to be misinterpreted. It is a _much_ more effective use of both our and everyone in our community's time if we add a topic or proposal to github and then have a forum (meeting) where we can discuss it _if necessary_ 'in person' (or remotely via voice) and add our conclusions/actions to github 
  + If we don't need to discuss something, great. This is really just for things where we find ourselves writing essays as responses or are organisational decisions.
+ Unstructured allocation of priorities for posterior discussion is not productive. We need to discuss results, ascertain priorities and then redirect our personal priorities in line with these
  + Priorities are also discussed at the beginning of each week with a colleague as a second level sanity check of alignment to furthering objectives

What I _do_ think might work well is if we meet once a fortnight or once a month to set priorities and review progress instead of meeting every week.

In terms of 1-to-1s, I still very much see the value in these. Having a forum to do a quick sanity check on priorities and discuss concerns/successes/frictions is a good thing 👍

**Comment by nelsonic** [comment]
Not having meetings is not _costing_ us any money. so it's not `priority-1`. 
see: https://github.com/dwyl/hq/issues/349#issuecomment-306205947

**Comment by nelsonic** [comment]
Not having meetings is not _costing_ us any money. so it's not `priority-1`. 
Not having management accounts to steer decision making is costing us at _least_ 1k/day. 
see: https://github.com/dwyl/hq/issues/349#issuecomment-306205947

**Comment by markwilliamfirth** [comment]
Closing as was decided not to continue meetings

**Comment by iteles** [comment]
This wasn't _decided_. This was _given up on_. I will revisit this when I have the energy for it, there are higher priorities.

**Comment by iteles** [comment]
Mobile UI 🙄

**Comment by iteles** [comment]
We no longer have this problem. All actions are captured on Github as issues.
