### ISSUE TITLE
Email Accountants about Bookkeeping

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#301]
Email Accountants about Bookkeeping

**Comment by nelsonic** [comment]
# _PLEASE_ DON'T READ THIS! IT'S NOT FOR YOU!!

When a person opens an issue to pay lip-service to "tracking" the task ✅❓ 
then adds _zero_ detail/checklist or follow-up so it's _impossible_ to "unpick" what was actually _done_ ... 😞

![image](https://user-images.githubusercontent.com/194400/51933340-fde4c280-23f8-11e9-8a0b-d35c548be3ae.png)

What was the _criteria_ for selecting a bookkeeper? What service was requested? What were the terms of engagement? What is the _system_ for producing the accounts? (_not "chuck everything in Xero and hope for the best..."_) 🤔 

This is still _haunting_ us 20 months later ... 💸
our accounts are _still_ a _mess_ because "ghost" shirked their responsibility instead of doing their job! 🙊 
Before we hired "ghost" they assured us they were going to study accounting part-time 🤓📚 
and use their knowledge/experience to help make our accounting systems work like a swiss watch. ⌚️ 
Turns out it's more "Clockwork Orange" than "Patek Philippe" ... 🍊 
It's a "black hole" of chaos that is probably going to force us out of business. ⌛️

Building a bootstrapped/revenue-funded company is _incredibly difficult_.  🏃 
I put my _faith_ in "ghost" as an "A Player" and it came back to bite me _really_ hard! 👻 > 🧛

The _last_ thing we needed was a work-shy snowflake who constantly complains about [_everything_](https://github.com/dwyl/hq/issues/168#issuecomment-282489707) 👎 
then takes a massive crap in the drinking well! 💩🚰 
and walks away with a payout pretending they did "nothing wrong" ... 😢 

![image](https://user-images.githubusercontent.com/194400/51933806-0db0d680-23fa-11e9-9c70-6d8cecadcb32.png)

If you have never had someone _super intelligent_ who you _trusted_ deliberately do as little work as possible while simultaneously _actively_ making things worse for your "baby", you don't know how this _feels_ ... Don't even _think_ about defending "ghost" as being a "victim" ... they are an [arsonist](https://en.wikipedia.org/wiki/Firefighter_arson)! 🏦🔥 
Go work on your own self-funded idea, gave it everything you have on all the evenings and weekends for a few years and then watch it _crumble_ after someone you _trust_ sucker-punches you repeatedly!
You can work 80 hour weeks for *years* to build a company and have it all _evaporate_ because one person cannot be _bothered_ to do the job they were responsible (_and **generously** compensated_) for. 

# It's _soul destroying_. 😭
