### ISSUE TITLE
Feedback Application Plan

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#315]
Is this product being released publicly so other people can use is or is it just internal?

**Comment by nelsonic** [comment]
We can write a Blog Post about it once we ship it. 
We aren't _actively_ marketing it (_yet_) because we can't _support_ it (_yet_).
But as soon as we have a chance to "_flesh out_" the feature(s) a bit 
(_specifically with some real-time and embedding_) 
we could make it a _product_ that people can use on their websites/apps.
(_that was the idea from the start..._)

We need to "_dog-food_" it _internally_ first 🗣 💬 
and then "_pitch_" it (_for free_) to one of our _existing_ clients once we think it's stable. 💡

**Comment by nelsonic** [comment]
Have we _captured_ the Plan for the Feedback App _somewhere_...?

**Comment by markwilliamfirth** [comment]
@nelsonic as described in your comment here https://github.com/dwyl/hq/issues/315#issuecomment-300559785 the plan is:

- To dog-food the product internally
- To pitch it for free to one of our existing clients once we think it's stable

**Comment by iteles** [comment]
@markwilliamfirth We should capture that comment in the https://github.com/dwyl/feedback readme.

**Comment by markwilliamfirth** [comment]
@iteles good idea 👍

**Comment by markwilliamfirth** [comment]
Next step: move plan to md
