### ISSUE TITLE
Allocation of budget to employee benefits

### ISSUE THREAD

**Issue by ghost** [dwyl/hq#331]
Moved from: https://github.com/dwyl/hq/issues/146

Current proposal:

pp py = per person per year
pp pm = per person per month

dwyl summer travel costs dwyl/summer#51 - £100 pp py
large quarterly events e.g. crystal maze #292 - £240 pp py
Headphones #147 with a 2-year warranty is equal to £100 pp py

We could also add benefits for:

Birthdays £30 pp py
8 monthly get togethers a year in months without large quarterly staff events £240 pp py
Total comes to £710 pp py
Which is £59.17 pp pm

Research suggests other tech companies are offering employee benefits in the range of £55 - £110 pp pm

**Comment by markwilliamfirth** [comment]
Decided by @iteles that this should wait until our financial position is clearer https://github.com/dwyl/hq/issues/146#issuecomment-301472836

**Comment by iteles** [comment]
And that issue was never complete so this issue wasn't revisited. Closing because there's a lot of noise, documented in the high priority issues so we can return to it afresh once we _know_ our  financial position a little better.

In the meantime we have continued to offer accommodation for dwylsummer and have team dinners and outings whenever there is a  good idea of what to do or when a group of us is together!
