### ISSUE TITLE
CU Water Project

### ISSUE THREAD

**Issue by ghost** [dwyl/hq#348]
Website
Open to the public randomised control trial of the effects of drinking water on weight
Applying for a funding grant

[Proposal](https://docs.google.com/document/d/1KAjQMyjEMZe_L_OozaMBwLP6u7r6s6v-vn9ZdSI74mQ/edit)

**Comment by markwilliamfirth** [comment]
Mark has sent email to request call

**Comment by markwilliamfirth** [comment]
User flow: https://drive.google.com/open?id=0B0XeQ2t5WSK2ckw2WDRjbU1pNnc

**Comment by iteles** [comment]
My notes from the call: 
+ Thin data so far on water's effect on weight, still need to know:
  + Best volume of water to drink
  + Best time of day to drink water
+ Best way to address this is a randomised control trial and large numbers can be obtained by having these as self-enrolled and self-reported studies on the web

This one:
+ 6 months trial
+ This is a pragmatic trial - whether people follow it or not isn't important, whether there's an effect if you _tell_ them to do it is the more important piece
+ Multiple possible methodological studies throughout


Base flow:
+ Click link to join study
+ Informed consent
  + Possible interactive consent based on a number of questions where volunteers can move suggested volumes of water up and down according to their preferences
  + Automatic (opaque) assignment to observation group or randomised control trial group
+ Enter demographic data (mostly optional) including email & password
+ Volunteers receive message saying their data is being processed and they will receive email in 48 hours
  + Ethics requirement of waiting 24 hours and also ensures they are committed
+ Email sent within 48 hours giving them access to their dashboard (permissions blocked for 48 hours from sign up)
+ Dashboard includes message on which group they have been assigned to by the computer
  + Dashboard is visual representation of the data points they have entered (weight over time, pie chart of compliance, etc)
+ Randomisation only happens when user comes back in to ensure it doesn’t take people who aren’t going to participate into account
  + Simple randomisation at first
  + Possible second randomisation on whether water should be consumed _before_ a meal
+ Possibly offer opportunity to come back once a week to enter data
  + Possibly via existing tools with APIs where we can pull in the data
  + Possibly send email every 7 days for them to enter data - if no data is entered stop
+ Withdrawal from trial at any point is possible (still relevant to get their final weight)
+ Email to be sent at the end of the 6 months asking them to enter final weight
+ Simple admin backend that provides access to data but no visualisation as of yet


Further notes:
+ **Key**: in 6 months they come back and tell you their weight
  + Continuous inputting of data is less important (burden to participant vs amount of info we need)
+ No CMS
+ Simple, attractive and not overwhelming design
+ Possibly having multiple URLs for determining the source of the volunteer
+ Data privacy has to follow Good Clinical Practice guidelines
  + https://www.openclinica.com
+ Comparable study received 10,000 hits a day when URL placed on NHS Choices

Actions:
+ [ ] Amanda to send through Good Clinical Practice guidelines
+ [ ] @markwilliamfirth and @nogainbar to review possible user flows
+ [ ] @nogainbar to provide design estimates for various options
+ [ ] @markwilliamfirth to send simple set of contextualised estimates to AB 

**Deadline: 22nd June 2017**

**Comment by markwilliamfirth** [comment]
Additional notes:

This project is being built in connection with a trial to drink a certain amount of water per day (volumes ab libitum or volumes before meals).

The trial will collect data from users (water consumption, weight, mood [optional])

Note: users can also track their water consumption by downloading a paper form

- This is an app that informs, enrols, tracks and motivates users to drink a certain amount of water
  - Mainly a randomised controlled study
    - Pragmatic study
    - Explanatory study
  - Also an observational study on users who choose their intake amounts
- Simple, clean design
- Informs people about the trial
- We want to know where people came from (NHS website, Google, Facebook, etc)
- Allows people to give informed consent (24h delay required for ethics)
  - Real informed consent
  - Test consent - answer questions - don’t let it look like an exam
  - Almost like if a researcher was talking to the trial participant
  - This could be built as a separate interactive tool
- Collect baseline demographic data
- Allows people to keep coming back to input their data into the 6-month trial (and beyond)
- Mobile app that can send people reminders to reach target
- Users can track how much water they’re drinking - click glasses/bottles to add to total, shows percentage
- User accounts with password reset functionality
- User page with visual charts / dashboard of water, weight and mood (if applicable)
- Users reminded by email notification (push notification?) every 7 days first thing in the morning (remind to wear the same clothing whenever weighing)
- If users don't stick to the trial, send a message "we’ve noticed you haven’t been entering data - would you prefer to enter it less frequently?" - this is because primary trial outcome is weight after 6 months, all other data is associated with secondary outcomes of the trial
- There are particular standards for health research data (Open Clinica)

Quote to be provided
- Costed in a modular fashion for additional 'complexities'

**Comment by markwilliamfirth** [comment]
[User Flow Draft](https://docs.google.com/document/d/11ICp5QV-oq2QImx6glNXDsGAXLV7zUSrt0t_s54HMZI/edit)

**Comment by markwilliamfirth** [comment]
Mark to ask Amanda:
- Estimated project start and end date
- How important it was that she knows where people come from?

@nogainbar 
To speak to Inês regarding:
- How much opportunity there will be for user testing will there will be during development? Will there be user testing sessions?

and to provide quotes:
- Low - MVP quote
- Medium - over-estimate quote
- High - high fidelity quote
- Quotes for design extensions
  - Complex interactive consent / onboarding process
  - Complex dashboard
  - Complex email reminders

**Comment by iteles** [comment]
@nogainbar We will plan in some user testing during development but I imagine we would add 1.5-2 days of our time at most (budgets are always tight at CU) to get it set up and then run by the PO.

**Comment by markwilliamfirth** [comment]
I've sent a message to Amanda

**Comment by markwilliamfirth** [comment]
The critical deadline is 19th July deadline for application but the proposal needs sign off my finance and research lead at City University before that.  The very earliest the project could start would be around October 2017 but the start date is flexible and a launch next year would be fine too.
 
It is not at all crucial to know where people have come from. If this adds great complexity lets leave it. It just helps to inform future recruitment of participants in online research to know what works well.
 
We could ask people prior to randomization when we are trying to create a hurdle or burden of participation to weed out those who are likely to drop out later but after randomization we want to keep the burden of participation to a minimum so that they don’t drop out!
 
The trial is open to anyone who is adult and for whom drinking extra water is not contraindicated (a few rare people which we will identify during the informed consent process).
 
It would be nice if there were full accessibility to include, for example, blind people but this is not a pre-requisite and I would leave out anything that increases the cost noticeably.

**Comment by markwilliamfirth** [comment]
@nogainbar Amanda has replied (as above) - does that help? How are the quotes coming along?

**Comment by markwilliamfirth** [comment]
[Proposal](https://docs.google.com/document/d/1KAjQMyjEMZe_L_OozaMBwLP6u7r6s6v-vn9ZdSI74mQ/edit) has been completed, requires review from @iteles before sending to Amanda

**Comment by markwilliamfirth** [comment]
Sent yesterday

**Comment by markwilliamfirth** [comment]
Amanda will be applying for funding for this. If we are successful the project will likely begin late August or September

**Comment by iteles** [comment]
Lowering the priority on this for now as there isn't much we can do about it.

@markwilliamfirth I spent 1 hour on this call + maybe another 30 minutes in brief conversations with you and Noga + 2 hours of a skimmed review of the proposal and discussing my thoughts with you. I didn't add a time estimate though as you were the one taking point on this.

Please log the time you spent on it and pulling the proposal together.

**Comment by markwilliamfirth** [comment]
@iteles this is still high priority, but has a dependency on it

**Comment by iteles** [comment]
Please see my question above on time https://github.com/dwyl/hq/issues/348#issuecomment-327008620

**Comment by markwilliamfirth** [comment]
@iteles this was sent back in July and I can't remember how much time was spent on it. I would hazard a guess at a day in total maybe?

**Comment by iteles** [comment]
This didn't come to fruition and the client wasn't very enthused with the late proposal and having to chase us for it multiple times.

The initial bout of funding didn't come through and she was less interested after that.
