### ISSUE TITLE
Change address for banking & HMRC correspondence

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#359]
@markwilliamfirth When you first joined you changed some of the correspondence addresses to the flat on Palmers Road.

We're leaving at the end of the month so please change this to the office address asap so that letters sent out the week after next aren't lost.

**Comment by markwilliamfirth** [comment]
@iteles now that we know we're staying in Focus Hub for at least the next 8 months and bearing in mind you guys are off to Portugal, should I set all addresses to 16 Palmers Rd?

**Comment by iteles** [comment]
👍 That's exactly what I was thinking with 'office address' 👍

**Comment by markwilliamfirth** [comment]
@iteles sorry I didn't phrase well - I mean should I update all addresses - including the MDC ones?

**Comment by iteles** [comment]
@markwilliamfirth Yes, let's do that. We need a central place where everyone has access to the post. Will require a change on our website too.

**Comment by iteles** [comment]
@markwilliamfirth We've now left the flat. Is this done?

**Comment by markwilliamfirth** [comment]
The registered office address has been updated to:

Focus Hub,
Unit 16 Palmers Road,
London
E2 0SY
United Kingdom

Your, mine and Nelson's correspondence address is linked to the registered office address, so all correspondence will also now come to Focus Hub. Your and Nelson's home address has remained recorded at 104 MDC.

The Santander business and Director correspondence addresses have also been updated. The registered office has yet to be updated because they have to wait until it is updated on Companies House Beta - I'll call back once it is.

I've emailed the Co-op to update the address there.

**Comment by markwilliamfirth** [comment]
@nelsonic @iteles 

Santander's recorded companies house address and our trading address has been updated to:

Focus Hub,
Unit 16 Palmers Road,
London
E2 0SY
United Kingdom

This means that you need to use this as the billing address for card payments from now on

08007316666 is the number to call if there are any issues

**Comment by markwilliamfirth** [comment]
The following have also been updated to:

Focus Hub,
Unit 16 Palmers Road,
London
E2 0SY

**Coop**
- Correspondence address
- Trading address

**HMRC**
- Corporation Tax Registered address
- Corporation Tax Communication address
- PAYE for employers Business Address	
- PAYE for employers Communication address	
- VAT Principal Place of Business address

Principal Place of Business address
