### ISSUE TITLE
Build our own cms

### ISSUE THREAD

**Issue by shouston3** [dwyl/hq#367]
There isn't currently a Phoenix CMS.

Using a CMS written in another language isn't going to play well with phoenix and will undoubtably lead to [nasty code](https://github.com/LDMW/app/blob/master/web/controllers/resources.ex) which won't be the most maintainable (plus inefficiencies in how we make our queries and we won't have that much control with how our database is optimised for our phoenix apps) (seeing how phoenix optimises this through model relations is really useful and we are wasting it with other cms implementations).

Building a CMS in phoenix won't be _that_ difficult.

Once built we will be able to make new views/edit views really fast (phoenix's implementation through generators seems much simpler and more powerful than other cms implementations (wagtail doesn't even come close))

From working with wagtail, I honestly feel that we would be much better off implementing our own cms and feel that it would be well worth our time building it

**Comment by nelsonic** [comment]
@shouston3 that's the _reason_ we _agreed_ to use Wagtail for LDMW ... 😉 
(_it's not because we think Wagtail is "perfect", but it was a way for you & @Danwhy to get "exposure" to a reasonably popular CMS ..._)

Using a _few_ CMSes is the _best_ way to learn the "workflow". 
We can do a _much_ better job than Wagtail. 

Please take some time to look at a couple more CMSes for UI/workflow/features 
`.then` read through the issues in: https://github.com/dwyl/adoro

The key features of dwyl's CMS will be:
+ One-click Install to Heroku (_similar to Wordpress_) see: https://github.com/dwyl/adoro/issues/9
+ Content Editor
  + All content written in Markdown with "live editor" (_written in Elm so it's **rock solid**_)
  + Image floating done using basic styles borrowed from Tachyons 
  + Content should be stored in a Version Control system i.e. GitHub ... 
+ Content is rendered as AMP-Compliant HTML by _default_ using: https://github.com/dwyl/amp-elixir (_**superb** work BTW!_) 😉 
+ Drag-and-Drop Image upload via AWS Lambda with auto-resizing and optimization for mobile https://github.com/dwyl/image-uploads we need to investigate how to _simplify_ adding Environment Variables to Heroku-based web apps ... ***OR*** we need to investigate how easy it is to deploy to "LightSail" (_aka "AWS Lite"_) see: https://github.com/dwyl/learn-amazon-web-services/issues/15
+ Themes `should` be _compatible_ with an _existing_ CMS, WordPress would be a _good_ choice because the front-end of CMSes (_that people see_) is the part that _matters_.

**Comment by shouston3** [comment]
I'm so up for this if/when you want to start building it

Closing and continuing [here](https://github.com/dwyl/adoro/issues/100)

**Comment by nelsonic** [comment]
@shouston3 your input might be required on the "core product" quite soon, but if you want to help build the MVP CMS let me know when you have time on https://github.com/dwyl/adoro/issues/100
