### ISSUE TITLE
VAT Return

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#370]
We need to submit a VAT return for the period 01.05.17 to 31.07.17

Deadline: 7th September 2017

**Comment by iteles** [comment]
I have some outstanding receipts. I will aim to upload these over the course of the next week.

**Comment by iteles** [comment]
The outstanding receipts I have with me have been input into Xero (all under 'Office supplies' as the correct categories are not set up yet #339), though there may still be some in the UK outstanding. Please do go through the bank statement to pick up on these expenses.

I have a number of Portuguese ones that I can't enter because the app does not support euros, but these should not impact VAT. Let me know if there's any category of international VAT we can claim back and I'll take another look through these.

**Comment by markwilliamfirth** [comment]
Submitted, net due was 45,959.74
