### ISSUE TITLE
Who do we want to work with?

### ISSUE THREAD

**Issue by ghost** [dwyl/hq#379]
Moved from https://github.com/dwyl/dwyl-site/issues/68 (Who do we want to work with?)

Current suggestions:
British Museum
British Library
Victoria and Albert Museum
Bodleian Library
National Archives
http://www.opencompany.org/directory/

Assigning Inês as this comes under biz dev

Dependant on #328

**Comment by Jbarget** [comment]
[Welcome Collection](https://wellcomecollection.org)?

**Comment by nelsonic** [comment]
This is a [*moot point*](https://en.wiktionary.org/wiki/moot_point) because it _assumes_ that we _want_ to work with (**`for`**) _any_ organisation on a "consulting" basis.  It has _never_ been our goal to build apps **`for`** any client. Building apps for clients was _always_ a "stop gap" to get funds to build our _own_ products. Sadly, (_from **my** perspective_) the day-to-day running of a "Web App Agency" took over and the "dream" of building our own products _evaporated_. 

To be _clear_ I have _nothing_ "_against_" any of the fine organisations (_listed above_).
If my goal was to have a list of prestigious names on a "client list" and make zero "surplus income",
I would consider "pitching" consulting work to any/all of these institutions! 
But my _goal_ is to build a _software **product**_ that serves _many_ people without much "manual customisation"; not to "trade hours for dollars" and have nothing _residual_ to show for it.

Closing.
