### ISSUE TITLE
Google Apps for Work?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#38]
Is it time to migrate to Google for our Company Email?
Simply so we can begin *testing* different email addresses.
https://www.google.com/work/apps/business/pricing.html
e.g: hello+websummit@dwyl.co

There are *many* other advantages:
+ Calendars Work.
+ Spam Filtering works.

The only question we need to ask is: will it cost us £3/$5/€4 per month for each email address:
+ hello@
+ ines@
+ nelson@
+ cash@
+ etc...

**Comment by iteles** [comment]
That adds up quite quickly. We're fans of having quite a few different email addresses...!

Seeing as our business cards for the websummit _don't_ have this printed on them for the email address, could we MUP this by creating a websummit@dwyl.io email address in ZohoMail and having all of the `mailto` possibilities on the `/websummit` endpoint for the website email to _that_ email instead of just hello@dwyl.io?

If we get hits we can take it into consideration when we look into the cost/benefit of this next week after the #websummit :+1:

**Comment by iteles** [comment]
Been using Google Apps for Work for a few months and working well.
