### ISSUE TITLE
Refresh Coop Bank Feed

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#386]
@iteles it seems the bank feed for coop stopped on May 15 - can you refresh please?

**Comment by markwilliamfirth** [comment]
Linked to #370

**Comment by iteles** [comment]
Seemingly not. It just endlessly hangs (5 minutes and counting).
<img width="163" alt="screen shot 2017-09-05 at 15 11 52" src="https://user-images.githubusercontent.com/4185328/30065395-94a15642-924c-11e7-993c-b32bc531ddd8.png">

Historically we have always done our VAT returns based on invoices sent out in the period rather than cash in the bank (for simplicity) so unless we are changing this (which I believe HMRC may need to be notified of and would require a fair amount of calculations on our side around what has or has not been accounted for), this shouldn't be a blocker for the VAT return specifically.

**Comment by markwilliamfirth** [comment]
@iteles it's not just invoices sent out, it's money received and expenses etc - it's everything

Can you contact xero support and ask why it won't refresh? (I would but I don't have coop credentials, so there will not be much point in me doing so)

**Comment by iteles** [comment]
The only thing that we use use the Coop Bank for is to receive invoices, so there won't be any additional money received or expenses that come out of there.

Happy to send you a PDF statement for the quarter until #219 is sorted, but all of the payments made in were captured against the relevant invoices in Xero as well (Xero is up to date with payments made into Coop up to 4-Sept).

I can call Xero but I'm on holiday today (replying here as this was marked priority 1) so it won't be today.

**Comment by iteles** [comment]
Done.

**Comment by markwilliamfirth** [comment]
Requires refresh again

**Comment by iteles** [comment]
This is done but the amount is incorrect (6k over on the balance). I'm not sure why.
For your purposes @markwilliamfirth shall I sent you the last few months as a PDF so you can see where the discrepancy comes from?

@markwilliamfirth The reason this keeps failing is because Xero doesn't have a sophisticated interface with the CBank and because we use a one-time authentication token, it's wrong every time.

**Comment by markwilliamfirth** [comment]
@iteles yes PDF would help if possible

**Comment by markwilliamfirth** [comment]
PDF issue moved to #393
