### ISSUE TITLE
Old Amazon still taking payments

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#388]
a 14.95 payment came out of the bank account on 7 september - I haven't made any purchases on the new account ( #218 ) and I removed the cards to the old account after we last used it so I don't know what caused it. I tried to log back in to the old account to check what happened - possibly a delayed payment? But it's now asking me for a code from the new ideaq email in order to log in so I'm unable to check.

**Comment by iteles** [comment]
Our audible account is still linked to the old email, so it's probably that. I'll get this swapped over.

Lowering the priority as it doesn't need to be done this week 👍

**Comment by markwilliamfirth** [comment]
@iteles I think I removed the cards from that too so I don't think it's that either - I might be wrong though

**Comment by markwilliamfirth** [comment]
I've marked this against the loan account for now as I can't seem to find a business purchase that matches this, please reopen if you know what this is

**Comment by iteles** [comment]
I figured out what this was. It's not the _old_ amazon account that was taking the payments, it's that rather than sharing the old amazon account's Prime membership (prepaid until end March 2018) with the new dwyl Amazon account  #49 , a _new_ prime membership was created for the new dwyl Amazon account.  🙄

I've now cancelled the new Prime membership account (under £30 spent on this in total happily) and shared the prepaid Prime membership.
