### ISSUE TITLE
Looking into personality profiles as a method for improved communication

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#409]
We all work in different ways and this can sometimes make for either very stressful or very harmonious work environments, particularly in a culture where there is maybe a little more reluctance to tell people when they are doing something that we don't really appreciate!

For example, if I work better digging straight into the code, but I know that my team mate has a need to think through a problem by themselves for a while and come up with an implementation plan to discuss alone first, I know that if I immediately pounce on them after my sprint planning session, I will stress them out and create unnecessary friction. It also means that I know _not_ to feel incredibly frustrated with them for _not_ immediately getting into the code _with_ me.

So how do we make everyone's lives a little easier by **giving each other insights into how we function best** and what is a problem for us?

Other than an awkward 'forcing' of heart-to-hearts, _I was reminded the other day in an HBR Review podcast that personality profiles are possibly a useful communication tool._ (I will have to find this again, it was just mentioned in passing in a conversation 😬 )
https://www.fastcompany.com/3044030/how-to-get-better-at-reading-and-reacting-to-coworkers-personalities

It seems to me, that knowing more about each other's working styles is advantageous in so many ways! It could lead to:
+ Better empathy within a team
+ Less friction
+ Potentially allowing for more balanced teams to be brought together (as well as an understanding of _why_ some people might not work together well)
But the question is, **is having a personality profile test done a good way to go about this?**

It could be problematic in a number of ways:
+ The information could be personal and people might not want to have it available to their colleagues (this includes me!!)
+ Putting a person in a specific box (personality 'definition') could end up being a self-fulfilling prophecy, with that person not wanting to 'venture outside' of their 'assigned' personality
+ The results could just be totally ignored

With the context that the results are to be _analysed_ and made usefully coherent and that this is just a guide which everyone is encouraged to step out of, it _may_ provide some interesting results.

As all of this is potentially quite personal and I don't want to make anyone uncomfortable, I propose that _I_ take one, see how I feel about sharing the results, share them and request feedback from dwylers around whether this is useful knowledge/tool to _them_ before we look into offering it as an _option_ to everyone.

**Comment by Cleop** [comment]
https://www.positiveintelligence.com/assessments/ - Anish had to complete this one at another workplace and he seemed to feel it was a good tool.

I don't know how helpful this is in terms of coding working styles but perhaps one to explore nonetheless!

Personally I don't feel averse to trying these kinds of things.

**Comment by rub1e** [comment]
I did one at my old job. (I've done many but only one was worth mentioning.) It was like Jung himself had peeled back the layers of my onion and captured the very essence of my being. Even then about 20% was complete bullplop.

I have huge misgivings about using these tools for anything other than personal introspection, however. 

The idea of outsourcing your team dynamics to an algorithm that you don't understand, based on psychological theory you don't understand, and then taking results that have been distilled into layman's terms so that you do kinda understand seems folly to me.

(I also think it's absolutely crackers to use this for recruitment, but thankfully no one's suggesting that.)

Even if you're happy with the idea in general, there are huge issues around the accuracy of the tests themselves - consider whether you've ever scored the same on two different personality tests, or the extent to which you consider yourself to have an immutable personality that's unaffected by context, or whether you've ever tried to guess the "right" answer... 

All that said, @iteles I'll bring mine in tomorrow and you can marvel at it :smile_cat: 

Some reading:
* https://www.vox.com/2014/7/15/5881947/myers-briggs-personality-test-meaningless
* https://rationalwiki.org/wiki/Myers-Briggs_Type_Indicator#Criticism
* https://www.wired.com/2015/05/the-myers-brigg-personality-test-is-bunk-but-i-dont-care/

**Comment by iteles** [comment]
Experience has shown me that this is usually ignored after a short while and there wasn't much engagement with the issue anyway :+1:
