### ISSUE TITLE
Removal of personal dwyl email addresses

### ISSUE THREAD

**Issue by samhstn** [dwyl/hq#471]
My email address `sam@dwyl.com` was deleted today without notice.

@iteles @rub1e could you clarify why this has happened? Have I lost my email data?

As a member of the dwyl community and a contributor to dwyl repositories, I would like to know the how personal `dwyl.com` email addresses are managed and what the process is for notifying dwyl email owners of when major changes to their email address may be happening.

**Comment by rub1e** [comment]
Hi @samhstn, from our previous chats I was under the impression this was just your forwarding address rather than a main email address (and therefore all your emails would be saved in your personal account).

`dwyl.com` email addresses are traditionally given out to those working with dwyl clients directly on projects so we have organisational clarity and communication, they're not given out to the wider community.  Seeing as you're now contracting for Harvey Nash and not dwyl (and we pay about £50 a year for each of these email addresses), this is just the next step in the process.

Obviously happy to reinstate it if you've got data that you need to pull etc. - I'll do it in the morning and let you know.

It's great you've brought this up as we certainly need to document this process in the `process handbook`! We'll get that done 👍

**Comment by samhstn** [comment]
I'm just glad that the data shouldn't be lost. I have important information on that email address and need it as soon as possible. I should be able to wait until tomorrow morning though.

**Comment by iteles** [comment]
Hey @samhstn, are you happy this issue was resolved and can be closed?

**Comment by samhstn** [comment]
Hey @iteles, all good, have had a chance to back up my data, thanks 👍
