### ISSUE TITLE
Octobox - Untangle your GitHub Notifications

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#498]
@iteles this _might_ be relevant to you ... https://octobox.io  https://github.com/octobox/octobox
You _know_ it's good because @andrew made it ...  ❤️ 

![image](https://user-images.githubusercontent.com/194400/46684168-f3a07d80-cbe9-11e8-99e6-b37500e438cf.png)

![image](https://user-images.githubusercontent.com/194400/46684186-fef3a900-cbe9-11e8-8829-dc2d16ee2169.png)

**Comment by andrew** [comment]
👋 if you have any questions or feedback

**Comment by iteles** [comment]
I used Octobox for quite a while a LOVED it! 
I stopped using it eventually only because I spend _all_ day in Github working on lots of smaller things and managing notifications so it was still more natural to me to just click the bell icon in github when I was done with my current thing than to keep heading back to Octobox (although this is where I would start every morning).

I would definitely use it all the time if I was writing code all day because that requires less back and forths ❤️ Recommended!
