### ISSUE TITLE
Credit in HMRC CT account

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#524]
When I logged into our HMRC account last week  to make sure the latest accounts had been  filed correctly #406  noticed that there was a credit in our corporation tax account.

This was a hangover from last year where we had a credit because we paid into an erroneous  HMRC account (separate to the credit from deliberate overpayment of VAT 🤦‍♀️ https://github.com/dwyl/hq/issues/461#issuecomment-409606580) but @rub1e had already dealt with this and we received a refund shortly thereafter.

@rub1e Could you please double-check the refund and what's happening here?

**Comment by rub1e** [comment]
Yeah I've figured this out - it's actually quite straightforward (but I did misremember and therefore mislead you when we spoke over the phone, apologies)

* We paid our Q4 VAT payment "manually" so the money would come out of our account in that same financial year
* BUT I paid it into HMRC's Corporation Tax account instead of the VAT account by mistake
* AND then HMRC took our VAT payment a month later anyway because we've set up a direct debit (which is tricky to cancel)
* (AND additionally we'd been [overpaying VAT](https://github.com/dwyl/hq/issues/461#issuecomment-409606580) for some preceding quarters anyway)
* SO... at this point, we're in credit all over the place - our CT account is in credit because of the mistaken payment, and our VAT account is in credit because of the overpayments
----------------------
* HMRC then repaid our VAT credit (Xero, 14th September 2018) - so our VAT account is balanced
* The CT credit stayed with HMRC, so that accounts for just over 50% of the credit in our CT account.
----------------------
* BUT WAIT, THERE'S MORE: we've also got credit applied for a payment made in January 2019 (which I'm assuming you made on the instructions of our accountant?)
* AND we don't seem to *owe* anything at all - so presumably this means that whatever our accountants filed last week hasn't yet been processed
----------------------

So the upshot is:
* VAT is all balanced
* CT will have to be revisited; once it's clear that we've paid whatever we owe, I can ask for the remainder (if any) to be returned
* (There's also a small discrepancy in our PAYE account, but I think that can wait until I look at #515 as I'll need to go through payroll then anyway)

**Comment by iteles** [comment]
@rub1e Thanks for the sleuthing :shipit: 
The payment  made in January 2019 is our corporation tax for FY2017/18 - HMRC will treat this as a credit for now until the corporation tax filing is carried out by our accountants in the coming weeks (deadline: end April 2019). This is all correct.

I wasn't aware that we were in credit from last year (like you, I though this had  been returned to us), so could we please call them and ask them to return it? We need it this year, not as a credit for next!

**Comment by rub1e** [comment]
Yes of course - that all makes sense!

**Comment by rub1e** [comment]
On its way back to us now - we should check after the 18th to see if the repayment has been confirmed, and then it'll hit our account shortly after that

**Comment by iteles** [comment]
Confirmed! 🎉
