### ISSUE TITLE
Lessons learned from #websummit

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#55]
This year we went to the #28 web summit. Next year, being in Portugal and having a free ticket (10,000 female entrepreneurs are being offered one), makes it even more tempting.

What we need to understand is _whether it's actually **worthwhile**_ to attend for dwyl or whether it's a waste of a few days.

Therefore we need to write out _what we learned_ from attending this year.

**Comment by markwilliamfirth** [comment]
ok to close?

**Comment by nelsonic** [comment]
_Why_ is this `priority-4`...?
The companies/organisations that presented at Web Summit are _by definition_ successful.
If we aren't _prioritising_ learning from _successful_ people/orgs we are doomed to _mediocrity_. 
If anything this should be _un-prioritised_ until _someone_ has time to get it done. 
(_or if it were my decision it would be the **highest** priority because if we don't capture any of the learning from spending **several days** at WebSummit then the time was **wasted**!_)

Applying a _low_ priority _basically_ signals that it's _not important_ to learn from this event.

We should learn _exactly_ what it takes to be invited to be the _Keynote_ Speaker at WebSummit.
`then` set a **goal**/target to be invited to keynote at 2018 and implement a plan to achieve it.

**Comment by markwilliamfirth** [comment]
@nelsonic that was my estimate when grooming the ops backlog - please reassign priority if it is incorrect

**Comment by iteles** [comment]
Closing at it has been a long time since we attended ws.

Attending as a startup _for developers_ worked pretty well for Codecov. Attending as a startup that needs funding also helps you get a little recognition. Attending as someone who wants to start/be in a funded startup is probably also beneficial as you will likely learn _something_ either from talks or intelligently speaking to startups.

I personally have never started using a product off the back of seeing them at WebSummit and a _lot_ of the people on stalls just get lost because there are so many of them. I would hypothesise that as a startup you don't attend WS with the aim of getting (non developer) customers but rather with the aim of getting funding.

I personally found the talks far too high level with very few actual learnings. They are also far and away mostly aimed at VC funded startups and life in those startups so I find a lot of the information shared irrelevant.

A separate issue to be open on becoming a speaker at WS when it is relevant.
