### ISSUE TITLE
Add dwyl to hapiJS community

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#80]
http://www.hapijs.com/community

**Comment by hdrdavies** [comment]
:+1: I was thinking this the other day

**Comment by nelsonic** [comment]
![do it](https://media.giphy.com/media/wi8Ez1mwRcKGI/giphy.gif)

**Comment by markwilliamfirth** [comment]
ok to close?

**Comment by shouston3** [comment]
Someone needs to make a pr to [hapijs.com](https://github.com/hapijs/hapijs.com) (similar to [this pr](https://github.com/hapijs/hapijs.com/pull/471/files)) to close this.
I'm not sure, but I would say it would make the most sense for @iteles or @nelsonic to make the pr as to address the 'person' section better

**Comment by iteles** [comment]
@shouston3 Agreed, though I was looking at this just last week and wondering if we should given our new stack!

**Comment by markwilliamfirth** [comment]
Yeah I don't think our new stack has hapi so assumed it was irrelevant now, but wasn't sure... @nelsonic ?

**Comment by nelsonic** [comment]
@iteles we use Hapi for _several_ things and are _not_ going to change any _existing_ apps to "_PETE_". therefore it is _still_ a good plan for someone to prepare this PR.

**Comment by markwilliamfirth** [comment]
@nelsonic can you give me a quote about why you like hapi so I can make the pr?

(other examples of quotes are here https://hapijs.com/community)

**Comment by nelsonic** [comment]
Quote: 

> Hapi is our go-to framework for Node.js Web Applications. 
We have used Hapi for a number of client & internal Web App/API projects and everyone has been delighted with the results! Hapi is clearly built/maintained by an exceptionally experienced team and includes many features other frameworks do not even consider. Our favourite things are: testability is made incredibly easy (because "shot" is built in) and the event-based "hooks" for the plugin system which make writing extensions really easy. 
Once you start using Hapi you will find a treasure trove of incredibly useful functionality both within the core of framework and plugins built by the community. Thank you for making our lives easy/fun!

Feel free to edit/improve on this.

**Comment by rub1e** [comment]
Is this still a goer? Do we still use `hapi`? @nelsonic 

Are there other "communities" I should see about? Any of the PETE ones, for example? 

(Just respond positively if so - don't waste your time looking for them!!)

**Comment by nelsonic** [comment]
This _was_ a _major_ priority in 2017 when we were still doing work in Hapi.js ... 📆 
The quote was prepared ... all _someone_ had to do was create the PR. 😞 
I don't think this is relevant anymore. And adding @dwyl to "PETE" is basically pointless. 
Closing. Thanks. ☀️
