### ISSUE TITLE
Speak to IP lawyers about logo

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#93]
Our logo has been in use and in the public across github, social media, our website and [our merchandise] since the second quarter of 2015. We need to speak to IP lawyers about what rights this gives us. https://dribbble.com/shots/2619718-Fittle-icon

**Comment by nelsonic** [comment]
The longer we leave this the worse it will be ... we need a "take care of things" person ...

**Comment by markwilliamfirth** [comment]
@iteles do we have any lawyers that we currently deal with? Or are you happy for me to find some to acquire advice? Are there any other aims with regards to our IP aside from understanding our rights from using our logo over time? Are you hoping that it gives us certain rights? Are there other company's with similar logos to ours that you know of and do they know about us?

**Comment by markwilliamfirth** [comment]
Might start with these guys to see if we can get free advice:

IPO Information Centre information@ipo.gov.uk
Telephone: 0300 300 2000
Fax: 01633 817777
Monday to Friday, 9am to 5pm

**Comment by nelsonic** [comment]
We need to _trademark_ the logo, in addition to the dwyl brand name _before_ anything `else`.
@markwilliamfirth I would _recommend_ speaking to http://www.londonip.co.uk/contact-us _first_
![image](https://cloud.githubusercontent.com/assets/194400/22509309/77c3ee8e-e885-11e6-926f-379e85d350e9.png)

They do a "free" consultation.
Alternatively speak to the peeps at: http://www.bl.uk/business-and-ip-centre who will help. 👍

**Comment by iteles** [comment]
Notes on what has already been done:
+ Emailed 	clinics@cipa.org.uk in **late April 2015** but their IP clinics were being put on hold
  + Already chased
+ Also tried the clinic at the British Library and got this in return:
<img width="714" alt="screen shot 2017-01-28 at 09 52 09" src="https://cloud.githubusercontent.com/assets/4185328/22509453/fb38a3b8-e885-11e6-8d95-dcdff7228bbf.png">

**Comment by markwilliamfirth** [comment]
@nelsonic with regards to your point about registering a trade mark

Can't we trade mark the logo ourselves? Didn't you trademark, "[DWYL](https://www.ipo.gov.uk/tmcase/Results/1/UK00003103535)"?

Would it not be simple for me to do [the same](https://www.gov.uk/how-to-register-a-trade-mark) for the logo?

**Comment by markwilliamfirth** [comment]
I phoned London IP but they didn't have any lawyers available to talk to at that time so they said they would call me back.

I phoned the Business and IP Centre and they advised that using the logo without a trade mark gives us no rights, although they also mentioned they're not qualified to give legal advice and that we should seek the advice of a [qualified trade mark attorney](https://www.citma.org.uk/home).

Their advice seems to contradict the [gov.uk website](https://www.gov.uk/how-to-register-a-trade-mark/unregistered-trade-marks), which says:

>You may be able to stop someone using a similar trade mark to yours on their goods and services (known as ‘passing off’), even if you haven’t registered it.

I will speak to London IP when they get back to me and update.

**Comment by nelsonic** [comment]
@markwilliamfirth ***yes we can*** trademark the logo ourselves. ✅ 
let's do that on Monday. 📆  (_after annual returns, etc._)

**Comment by markwilliamfirth** [comment]
London IP called me back.

They said we do have some "common law" rights as we have already been trading with our logo. The level to which we can utilise these rights depends entirely on whether we qualify as having carried out **substantial use and advertising**, we're probably borderline in that sense, but it's difficult to assess - if we ever did want to enforce these rights we'd have to make a case.

We do have copyright rights, and we could argue that Fittle has infringed our copyright, especially due to the similarity in the green colour of the tick. Although the red colour at the top of the heart is different and they could argue it is a coincidence. If we wanted to do this we could serve them a cease and desist to their Australian address and reserve our right to pursue legal action, but that's probably as much as we could do. It would be difficult to take them to court, as they don't currently operate in the UK. On a side note, for any future work from contracted designers on logos and branding etc, we should ensure the contract states we retain the copyright and intellectual property (as opposed to the designer retaining it).

Fittle is Australian-based, so there is little we can do in terms of trade mark rights. They don't have a UK registered company or UK trademark, so providing we registered first in the UK, we'd retain the rights to the image. We could also register in Australia (before them, as they have not registered yet) to retain rights there, but we would have to 'utilise' our trade mark by trading in Australia within the next 5 years.

If we want to protect the logo in the UK, the next step is to register it. We can register two images within the same application. London IP advised us to register one with the green colour and one black and white version; this is because black and white versions protect against all colours should a similar logo from another company appear in future. There is a small chance that the application will be denied, as the heart with the tick may not be considered distinctive enough - this is something we should focus on in our application. The green colour does provide more distinctiveness, so there is also a chance that the black and white image may be denied and the green image will pass.

Following completion of the UK trade mark application we are able to use the UK as a base to extend our trade mark to the EU or internationally.

**Comment by markwilliamfirth** [comment]
@nelsonic what email did you use to register the `DWYL` trade mark?

<img width="836" alt="screen shot 2017-02-07 at 10 38 19" src="https://cloud.githubusercontent.com/assets/5732209/22687838/94ae8144-ed21-11e6-872b-795948d0acfc.png">

**Comment by iteles** [comment]
@markwilliamfirth I used `dwyl smith`.  It's the only one we had back then!

**Comment by markwilliamfirth** [comment]
Is this our logo? Or is it the white and green version on [dwyl.io](http://www.dwyl.io/)?

<img width="902" alt="screen shot 2017-02-07 at 13 58 13" src="https://cloud.githubusercontent.com/assets/5732209/22694147/f3977320-ed3d-11e6-96b1-b5433571edfe.png">

**Comment by iteles** [comment]
That's the one! It's really the shape - if it's on a dark background (like the website), we'll use the white version (the teal tick is just to make the tick stand out, a little bit of a gimmick)

**Comment by markwilliamfirth** [comment]
We have applied! 🎉 

<img width="549" alt="screen shot 2017-02-09 at 10 01 52" src="https://cloud.githubusercontent.com/assets/5732209/22778490/09423bde-eeaf-11e6-8a0f-0d3560a53200.png">

**Comment by nelsonic** [comment]
Once we have the trademark for the logo we should submit it to: http://www.logobook.com/object/hearts/ `#InboundLinks`

**Comment by markwilliamfirth** [comment]
We've received this in the post - trademark was granted - it's been uploaded to drive

**Comment by nelsonic** [comment]
@markwilliamfirth thanks for sorting this. 🎉
